kellyselden/ember-macro-helpers

addon/-build-computed.js, addon/collapse-keys.js, addon/computed-unsafe.js, addon/computed.js, addon/expand-property-list.js, addon/expand-property.js, addon/flatten-keys.js, addon/get-value-unsafe.js, addon/get-value.js, addon/is-computed.js, package.json, tests/helpers/named-test.js, tests/integration/computed-test.js, tests/unit/expand-property-list-test.js, tests/unit/expand-property-test.js, tests/unit/flatten-keys-test.js, tests/unit/get-value-test.js, tests/unit/is-computed-test.js
=> consolidate with ember-moment

addon/-build-computed.js, addon/computed-unsafe.js, addon/computed.js, tests/integration/computed-test.js
Resolves https://github.com/stefanpenner/ember-moment/issues/212
=> Fix literal

README.md, addon/-build-computed.js, tests/integration/computed-test.js, tests/integration/reads-test.js
to be used here https://github.com/rwjblue/ember-computed-decorators/pull/82
=> support ember-computed-decorators by modifying set

addon/normalize-array-key.js, tests/unit/normalize-array-key-test.js
https://github.com/cibernox/ember-cpm/pull/140
=> changes needed to support ember-cpm

.npmignore, .travis.yml, blueprints/.jshintrc, blueprints/macro-test/files/tests/unit/macros/__name__-test.js, blueprints/macro-test/index.js, blueprints/macro/curried/__root__/macros/__name__.js, blueprints/macro/index.js, blueprints/macro/normal/__root__/macros/__name__.js, node-tests/blueprints/macro-test-test.js, node-tests/blueprints/macro-test.js, node-tests/fixtures/macro-test/foo-bar-test.txt, node-tests/fixtures/macro/foo-bar-curried-spread.txt, node-tests/fixtures/macro/foo-bar-curried.txt, node-tests/fixtures/macro/foo-bar-spread.txt, node-tests/fixtures/macro/foo-bar.txt, node-tests/helpers/describe-blueprint.js, package.json
=> add a macro blueprint

README.md
Unless this addon has telepathic powers...
=> Readme: fix `curriedComputed` example

addon/-build-computed.js, addon/create-class-computed.js, package.json, tests/integration/create-class-computed-test.js
I would love to have @marcoow and @Turbo87 code reviews. Related PR https://github.com/kellyselden/ember-awesome-macros/pull/252.
=> add create-class-computed ability

addon/create-class-computed.js, tests/helpers/destroy.js, tests/integration/create-class-computed-test.js, tests/unit/create-class-computed-test.js
=> clean up references to destroyed objects

README.md
=> fix createClassComputed docs

README.md, addon/-build-computed.js, addon/lazy-computed.js, addon/lazy-curried-computed.js, tests/integration/lazy-computed-test.js
=> add lazyComputed

addon/create-class-computed.js
Fix for https://github.com/kellyselden/ember-awesome-macros/issues/330
=> only bind to `willDestroyElement` for components

addon/create-class-computed.js, tests/unit/create-class-computed-test.js
More info at https://github.com/emberjs/ember.js/issues/15246
=> eliminate rewriteComputed redundant calls

addon/get-value.js, tests/unit/get-value-test.js
prerec to fixing https://github.com/kellyselden/ember-awesome-macros/issues/337
=> add key invalidation support to getValue

addon/-build-computed.js, addon/create-class-computed.js, tests/integration/create-class-computed-test.js, tests/integration/lazy-computed-test.js
fixes https://github.com/kellyselden/ember-awesome-macros/issues/337
=> fix composed class computed

addon/create-class-computed.js, config/ember-try.js, package.json, tests/dummy/app/controllers/dummy.js, tests/dummy/app/macros/map-by.js, tests/dummy/app/models/child.js, tests/dummy/app/models/parent.js, tests/unit/controllers/dummy-test.js
Fixes https://github.com/kellyselden/ember-awesome-macros/issues/344
=> fix controllers + async model relationships

addon/collapse-key.js
=> use a more generic var name for array keys

addon/collapse-key.js, addon/normalize-array-key.js
=> add empty string comment

addon/-constants.js, addon/collapse-key.js, addon/create-class-computed.js, addon/normalize-array-key.js
=> create constants file for special array strings

addon/collapse-key.js
A little refactor of your work @shamcode in #130
=> get the collapse and recurse done earlier.

package.json, tests/unit/create-class-computed-test.js
Reverts kellyselden/ember-macro-helpers#145
=> Revert "Update eslint-config-sane to the latest version 🚀"

package-lock.json, package.json
https://github.com/kellyselden/ember-macro-helpers/pull/222#issuecomment-463130842
=> revert babel 7

package-lock.json, package.json
Reverts kellyselden/ember-macro-helpers#242
=> Revert "revert babel 7"

.eslintignore, .eslintrc.js, package.json, vendor/monkey-patch-ember-computed.js
=> Vendor ie11
